name: Document Build

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
      with:
        fetch-depth: 1

    - name: Pull the Docker image
      run: docker pull owaspisvs/isvs-docgenerator:latest
    # only use below when testing new container builds
    # - name: Build the Docker image
    #  run: docker build ./tools/docker --tag isvs-generator:latest

    - name: Generate python scripts (csv)
      run: docker run -v ${PWD}:/documents owaspisvs/isvs-docgenerator:latest 'cd /documents/tools && python3 export.py --format csv --lang en > OWASP_ISVS-SNAPSHOT.csv'
    - name: Generate python scripts (json)
      run: docker run -v ${PWD}:/documents owaspisvs/isvs-docgenerator:latest 'cd /documents/tools && python3 export.py --format json --lang en > OWASP_ISVS-SNAPSHOT.json'
    - name: Generate python scripts (xml)
      run: docker run -v ${PWD}:/documents owaspisvs/isvs-docgenerator:latest 'cd /documents/tools && python3 export.py --format xml --lang en > OWASP_ISVS-SNAPSHOT.xml'
    - name: Upload CSV export
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_ISVS-SNAPSHOT.csv
        path: tools/OWASP_ISVS-SNAPSHOT.csv
    - name: Upload JSON export
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_ISVS-SNAPSHOT.json
        path: tools/OWASP_ISVS-SNAPSHOT.json
    - name: Upload XML export
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_ISVS-SNAPSHOT.xml
        path: tools/OWASP_ISVS-SNAPSHOT.xml

    - name: Generate English PDF
      run: docker run --rm -u `id -u`:`id -g` -v ${PWD}:/pandoc iowaspisvs/isvs-docgenerator:latest '/pandoc_makedocs.sh en SNAPSHOT'
    - name: Upload English PDF
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_ISVS-SNAPSHOT-en.pdf
        path: OWASP_ISVS-SNAPSHOT-en.pdf
    - name: Upload English EPUB
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_ISVS-SNAPSHOT-en.epub
        path: OWASP_ISVS-SNAPSHOT-en.epub
    - name: Upload English DOCX
      uses: actions/upload-artifact@v1
      with:
        name: OWASP_ISVS-SNAPSHOT-en_WIP_.docx
        path: OWASP_ISVS-SNAPSHOT-en_WIP_.docx
    #  MOBI cannot be generated for now
    #- name: Upload English MOBI
    #  uses: actions/upload-artifact@v1
    #  with:
    #    name: OWASP_ISVS-SNAPSHOT-en.mobi
    #    path: OWASP_ISVS-SNAPSHOT-en.mobi